container_cpu:
  name: container_cpu
  measurement: "cpu"
  diff: false
  tag_keys: [cluster, namespace, pod_name]
  fields: [{name: value, data_type: ""}]


container_mem:
  name: container_mem
  measurement: "memory"
  diff: false
  tag_keys: [cluster, namespace, pod_name]
  fields: [{name: value, data_type: ""}]
